"""Konfiguration für das Wurf-Coach-Projekt."""

CAMERA_INDEX = 0
FRAME_WIDTH = 320
FRAME_HEIGHT = 240
MIN_MOTION_AREA = 500
THRESHOLD_VALUE = 25
DILATE_ITERATIONS = 2
THROW_HISTORY_LENGTH = 8
THROW_MIN_UPWARD_DELTA = 20
THROW_COOLDOWN_FRAMES = 30
THROW_ZONE_START_RATIO = 0.65
THROW_ZONE_END_RATIO = 0.35
EVALUATION_HISTORY_LENGTH = 8
EVALUATION_GOOD_DELTA = 35
SHOW_GRAY_WINDOW = True
SHOW_MASK_WINDOW = True
DRAW_THROW_ZONE = True
THROW_ZONE_RATIO = 0.4
